### ISSUE TITLE
mvn clean install error

### ISSUE THREAD

**Issue by tech-engin** [levyfan/kenlm-jni#2]
[INFO] --- exec-maven-plugin:1.6.0:exec (cmake) @ kenlm-jni ---
[ERROR] Command execution failed.
java.io.IOException: Cannot run program "cmake" (in directory "/home/techengin/kenlm-jni/target"): error=2, 没有那个文件或目录
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1048)
	at java.lang.Runtime.exec(Runtime.java:620)
	at org.apache.commons.exec.launcher.Java13CommandLauncher.exec(Java13CommandLauncher.java:61)

have more install detail?

**Comment by levyfan** [comment]
You should install cmake. Please check the README https://github.com/levyfan/kenlm-jni#installation
